version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: .env
    restart: always

  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - postgres
    restart: always
