# Generated by Django 4.2.6 on 2024-02-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('quantity_in_stock', models.PositiveIntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='backend_pro_id_209cd7_idx'), models.Index(fields=['name'], name='backend_pro_name_d4bd25_idx'), models.Index(fields=['description'], name='backend_pro_descrip_880a72_idx')],
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='backend_est_id_81b22a_idx'), models.Index(fields=['name'], name='backend_est_name_4408ea_idx'), models.Index(fields=['description'], name='backend_est_descrip_6dc376_idx')],
            },
        ),
    ]
